/// AppStrings provides localized string resources for Gujarati ('gu'),
/// Hindi ('hi'), and English ('en') for the Shiv Amrut Darshan app.
class AppStrings {
  AppStrings._();

  static const String appName = 'શિવ અમૃત દર્શન';

  static final Map<String, Map<String, String>> _strings = {
    'gu': {
      'app_title': 'શિવ અમૃત દર્શન',
      'app_subtitle': 'ભગવાન શિવના પવિત્ર ચરિત્ર અને ભક્તિની અદ્ભુત યાત્રા',
      'hero_subtitle': 'શિવ કથા, મંત્ર, સ્તોત્ર અને 12 જ્યોતિર્લિંગ - સૌ કંઈ એક જ સ્થાને',
      'select_language_title': 'શિવ અમૃત દર્શન',
      'select_language_subtitle': 'ભગવાન શિવના પવિત્ર ચરિત્ર અને ભક્તિની અદ્ભુત યાત્રા',
      'choose_language_prompt': 'તમારી ભાષા પસંદ કરો',
      'continue_btn': 'આગળ વધો',
      'nav_home': 'મુખ્ય પૃષ્ઠ',
      'nav_categories': 'શ્રેણીઓ',
      'nav_favorites': 'પસંદગી',
      'nav_settings': 'સેટિંગ્સ',
      'main_categories_header': 'મુખ્ય શ્રેણીઓ',
      'continue_reading': 'વાંચન ચાલુ રાખો',
      'recently_viewed': 'તાજેતરમાં જોયેલું',
      'favorites_preview': 'તમારી પસંદગી',
      'search_placeholder': 'શોધો (શીર્ષક અથવા વર્ણન)...',
      'category_search_placeholder': 'શ્રેણીમાં શોધો...',
      'no_results_title': 'કોઈ પરિણામ મળ્યા નથી',
      'no_results_desc': 'તમારા શોધ શબ્દ સાથે મેળ ખાતું કંઈ મળ્યું નથી.',
      'no_favorites_title': 'કોઈ પસંદગી ઉમેરી નથી',
      'no_favorites_desc': 'તમે હજી સુધી કોઈ કથા કે મંત્ર પસંદગીમાં ઉમેર્યો નથી.',
      'font_small': 'નાના',
      'font_medium': 'મધ્યમ',
      'font_large': 'મોટા',
      'font_extra_large': 'વિશાળ',
      'settings_title': 'સેટિંગ્સ',
      'settings_header_subtitle': 'તમારી ભક્તિમય વાંચન પસંદગીઓ ગોઠવો',
      'sec_preferences': 'પસંદગીઓ',
      'sec_support': 'સપોર્ટ અને શેર',
      'sec_legal': 'કાનૂની અને નીતિઓ',
      'sec_about': 'એપ્લિકેશન વિશે',
      'settings_language': 'એપ્લિકેશન ભાષા',
      'settings_theme': 'ડિસ્પ્લે થીમ',
      'settings_font_size': 'વાંચન અક્ષર કદ',
      'setting_share_app': 'એપ્લિકેશન શેર કરો',
      'setting_share_subtitle': 'મિત્રો અને પરિવાર સાથે શિવ અમૃત દર્શન શેર કરો',
      'setting_rate_app': 'એપ્લિકેશનને રેટ કરો',
      'setting_rate_subtitle': 'પ્લે સ્ટોર પર તમારો મૂલ્યવાન રેટિંગ અને પ્રતિસાદ આપો',
      'settings_about': 'અમારા વિશે',
      'settings_about_app': 'શિવ અમૃત દર્શન વિશે',
      'settings_about_subtitle': 'એપ્લિકેશન વિગતો, આવૃત્તિ અને માહિતી',
      'settings_privacy': 'ગોપનીયતા નીતિ',
      'settings_terms': 'નિયમો અને શરતો',
      'settings_version': 'એપ્લિકેશન આવૃત્તિ',
      'developer_name': 'શિવ અમૃત દર્શન ભક્તિ ટીમ',
      'copyright_text': '© 2026 શિવ અમૃત દર્શન. સર્વાધિકાર સુરક્ષિત.',
      'coming_soon_title': 'ટૂંક સમયમાં આવી રહ્યું છે',
      'coming_soon_desc':
          'આ ભાષા માટે ડેટા ઉપલબ્ધ થઈ રહ્યો છે. કૃપા કરીને ભાષા બદલો અથવા પાછળથી પ્રયાસ કરો.',
      'change_language': 'ભાષા બદલો',
      'error_loading_title': 'સામગ્રી લોડ થઈ શકી નથી',
      'error_loading_desc':
          'કૃપા કરીને તમારું ઇન્ટરનેટ કનેક્શન ચકાસો અને ફરી પ્રયાસ કરો.',
      'retry_btn': 'ફરી પ્રયાસ કરો',
      'read_more': 'વધુ વાંચો',
      'items_count': 'આઇટમ્સ',
      'share_text': 'શિવ અમૃત દર્શન એપ્લિકેશનમાંથી',
      'link_copied': 'લિંક નકલ કરી',
      'theme_light': 'લાઇટ (પ્રકાશ)',
      'theme_dark': 'ડાર્ક (ભક્તિ)',
      'theme_system': 'સિસ્ટમ',
      'about_description':
          'શિવ અમૃત દર્શન એ ભગવાન શિવના પવિત્ર ચરિત્ર, શિવ કથા, 12 જ્યોતિર્લિંગ, મંત્ર, સ્તોત્ર અને ભક્તિ અવતરણ ડિજિટલ સ્વરૂપે સરળતાથી વાંચવા માટેની એક ભક્તિમય એપ્લિકેશન છે. | Har Har Mahadev!',
      'cat_id1': 'શિવ કથા',
      'cat_id2': 'શિવ પુરાણ',
      'cat_id3': '12 જ્યોતિર્લિંગ',
      'cat_id4': 'શિવ મંત્ર',
      'cat_id5': 'શિવ સ્તોત્ર',
      'cat_id7': 'અવતરણ અને સ્ટેટસ',
      'nav_status': 'સ્ટેટસ',
      'status_empty_title': 'કોઈ સ્ટેટસ ઉપલબ્ધ નથી',
      'status_empty_desc': 'હાલમાં કોઈ ભક્તિ સ્ટેટસ ઉપલબ્ધ નથી. કૃપા કરીને ફરી પ્રયાસ કરો.',
      'status_category_empty_title': 'આ કેટેગરીમાં સ્ટેટસ નથી',
      'status_category_empty_desc': 'આ કેટેગરીમાં હાલમાં કોઈ સ્ટેટસ ઉપલબ્ધ નથી.',
      'status_attribution': 'શિવ અમૃત દર્શન',
      'daily_quote_label': 'આજનો શિવ સંદેશ',
      'daily_quote_unavailable': 'આજનો સંદેશ હાલમાં ઉપલબ્ધ નથી.',
      'share': 'શેર કરો',
    },
    'hi': {
      'app_title': 'शिव अमृत दर्शन',
      'app_subtitle': 'भगवान शिव के पावन चरित्र और भक्ति की अद्भुत यात्रा',
      'hero_subtitle': 'शिव कथा, मंत्र, स्तोत्र और 12 ज्योतिर्लिंग - सब एक स्थान पर',
      'select_language_title': 'शिव अमृत दर्शन',
      'select_language_subtitle': 'भगवान शिव के पावन चरित्र और भक्ति की अद्भुत यात्रा',
      'choose_language_prompt': 'अपनी भाषा चुनें',
      'continue_btn': 'आगे बढ़ें',
      'nav_home': 'मुख्य पृष्ठ',
      'nav_categories': 'श्रेणियाँ',
      'nav_favorites': 'पसंदीदा',
      'nav_settings': 'सेटिंग्स',
      'main_categories_header': 'मुख्य श्रेणियाँ',
      'continue_reading': 'पढ़ना जारी रखें',
      'recently_viewed': 'हाल ही में देखा गया',
      'favorites_preview': 'आपकी पसंदीदा सामग्री',
      'search_placeholder': 'खोजें (शीर्षक या विवरण)...',
      'category_search_placeholder': 'श्रेणी में खोजें...',
      'no_results_title': 'कोई परिणाम नहीं मिला',
      'no_results_desc': 'आपके खोज शब्द से मेल खाने वाली कोई सामग्री नहीं मिली।',
      'no_favorites_title': 'कोई पसंदीदा नहीं जोड़ा गया',
      'no_favorites_desc': 'आपने अभी तक कोई पसंदीदा कथा या मंत्र नहीं जोड़ा है।',
      'coming_soon_title': 'शीघ्र आ रहा है',
      'coming_soon_desc':
          'इस भाषा की सामग्री जल्द उपलब्ध होगी। कृपया भाषा बदलें या बाद में प्रयास करें।',
      'change_language': 'भाषा बदलें',
      'error_loading_title': 'सामग्री लोड नहीं हो सकी',
      'error_loading_desc':
          'कृपया अपना इंटरनेट कनेक्शन जांचें और पुनः प्रयास करें।',
      'retry_btn': 'पुनः प्रयास करें',
      'read_more': 'और पढ़ें',
      'items_count': 'सामग्री',
      'share_text': 'शिव अमृत दर्शन ऐप से',
      'link_copied': 'लिंक कॉपी किया गया',
      'theme_light': 'लाइट (प्रकाश)',
      'theme_dark': 'डार्क (भक्ति)',
      'theme_system': 'सिस्टम',
      'font_small': 'छोटा',
      'font_medium': 'मध्यम',
      'font_large': 'बड़ा',
      'font_extra_large': 'अति बड़ा',
      'settings_title': 'सेटिंग्स',
      'settings_header_subtitle': 'अपने भक्ति अनुभव को निजीकृत करें',
      'sec_preferences': 'पसंद',
      'sec_support': 'सहायता एवं साझा करें',
      'sec_legal': 'कानूनी एवं नीतियाँ',
      'sec_about': 'ऐप के बारे में',
      'settings_language': 'ऐप भाषा',
      'settings_theme': 'थीम',
      'settings_font_size': 'अक्षर का आकार',
      'setting_share_app': 'ऐप शेयर करें',
      'setting_share_subtitle': 'मित्रों और परिवार के साथ शिव अमृत दर्शन साझा करें',
      'setting_rate_app': 'ऐप को रेट करें',
      'setting_rate_subtitle': 'प्ले स्टोर पर अपनी बहुमूल्य रेटिंग दें',
      'settings_about': 'हमारे बारे में',
      'settings_about_app': 'शिव अमृत दर्शन के बारे में',
      'settings_about_subtitle': 'ऐप संस्करण और जानकारी',
      'settings_privacy': 'गोपनीयता नीति',
      'settings_terms': 'नियम एवं शर्तें',
      'settings_version': 'ऐप संस्करण',
      'developer_name': 'शिव अमृत दर्शन भक्ति टीम',
      'copyright_text': '© 2026 शिव अमृत दर्शन। सर्वाधिकार सुरक्षित।',
      'about_description':
          'शिव अमृत दर्शन भगवान शिव के पावन चरित्र, शिव कथा, 12 ज्योतिर्लिंग, मंत्र, स्तोत्र और भक्ति उद्धरण को समर्पित एक भक्तिपूर्ण ऐप है। हर हर महादेव!',
      'cat_id1': 'शिव कथा',
      'cat_id2': 'शिव पुराण',
      'cat_id3': '12 ज्योतिर्लिंग',
      'cat_id4': 'शिव मंत्र',
      'cat_id5': 'शिव स्तोत्र',
      'cat_id7': 'उद्धरण और स्टेटस',
      'nav_status': 'स्टेटस',
      'status_empty_title': 'कोई स्टेटस उपलब्ध नहीं',
      'status_empty_desc': 'अभी कोई भक्ति स्टेटस उपलब्ध नहीं है। कृपया पुनः प्रयास करें।',
      'status_category_empty_title': 'इस श्रेणी में स्टेटस नहीं है',
      'status_category_empty_desc': 'इस श्रेणी में अभी कोई स्टेटस उपलब्ध नहीं है।',
      'status_attribution': 'शिव अमृत दर्शन',
      'daily_quote_label': 'आज का शिव संदेश',
      'daily_quote_unavailable': 'आज का संदेश अभी उपलब्ध नहीं है।',
      'share': 'शेयर करें',
    },
    'en': {
      'app_title': 'Shiv Amrut Darshan',
      'app_subtitle':
          'A Divine Journey into the Life & Teachings of Lord Shiva',
      'hero_subtitle':
          'Explore Shiv Katha, 12 Jyotirlingas, Mantras, Stotras and divine Quotes',
      'select_language_title': 'Shiv Amrut Darshan',
      'select_language_subtitle':
          'A Divine Journey into the Life & Teachings of Lord Shiva',
      'choose_language_prompt': 'Select Your Language',
      'continue_btn': 'Continue',
      'nav_home': 'Home',
      'nav_categories': 'Categories',
      'nav_favorites': 'Favorites',
      'nav_settings': 'Settings',
      'main_categories_header': 'Main Categories',
      'continue_reading': 'Continue Reading',
      'recently_viewed': 'Recently Viewed',
      'favorites_preview': 'Your Favorites',
      'search_placeholder': 'Search title or description...',
      'category_search_placeholder': 'Search in category...',
      'no_results_title': 'No Results Found',
      'no_results_desc': 'We couldn\'t find any match for your search term.',
      'no_favorites_title': 'No Favorites Saved',
      'no_favorites_desc': 'Items you bookmark will appear here.',
      'coming_soon_title': 'Coming Soon',
      'coming_soon_desc':
          'Data for this language is being prepared. Please switch to Gujarati or check back soon.',
      'change_language': 'Change Language',
      'error_loading_title': 'Unable to Load Content',
      'error_loading_desc':
          'Please check your internet connection and try again.',
      'retry_btn': 'Retry',
      'read_more': 'Read More',
      'items_count': 'items',
      'share_text': 'Shared from Shiv Amrut Darshan App',
      'link_copied': 'Link copied to clipboard',
      'theme_light': 'Light Mode',
      'theme_dark': 'Spiritual Dark Mode',
      'theme_system': 'System Default',
      'font_small': 'Small',
      'font_medium': 'Medium',
      'font_large': 'Large',
      'settings_title': 'Settings',
      'settings_language': 'App Language',
      'settings_theme': 'App Theme',
      'settings_font_size': 'Reading Font Size',
      'setting_share_app': 'Share App',
      'setting_share_subtitle': 'Share the divine Shiv Amrut Darshan with friends and family',
      'setting_rate_app': 'Rate App',
      'setting_rate_subtitle': 'Give your valuable rating and feedback on Play Store',
      'sec_support': 'Support & Share',
      'sec_legal': 'Legal & Policies',
      'settings_about': 'About Shiv Amrut Darshan',
      'settings_privacy': 'Privacy Policy',
      'settings_version': 'App Version',
      'about_description':
          'Shiv Amrut Darshan is a spiritual application dedicated to presenting the divine stories, eternal mantras, sacred Jyotirlingas, and devotional teachings of Lord Shiva. Har Har Mahadev!',
      'cat_id1': 'Shiv Katha',
      'cat_id2': 'Shiv Puran',
      'cat_id3': '12 Jyotirlingas',
      'cat_id4': 'Shiv Mantras',
      'cat_id5': 'Shiv Stotras',
      'cat_id7': 'Quotes & Status',
      'nav_status': 'Status',
      'status_empty_title': 'No Statuses Available',
      'status_empty_desc': 'No devotional statuses are available right now. Please try again later.',
      'status_category_empty_title': 'No Status in This Category',
      'status_category_empty_desc': 'No statuses are available in this category right now.',
      'status_attribution': 'Shiv Amrut Darshan',
      'daily_quote_label': 'Daily Shiv Quote',
      'daily_quote_unavailable': 'Daily quote is not available right now.',
      'share': 'Share',
    },
  };

  static String get(String key, String langCode) {
    final langMap = _strings[langCode] ?? _strings['gu']!;
    return langMap[key] ?? _strings['en']?[key] ?? key;
  }
}
